

				serverAddr = "193.123.85.124"
                serverPort = 7000
                auth.token = "5X7zeUnsdOESxH#J"
				webServer.addr="127.0.0.1"
				webServer.port=8888
				webServer.user="admin"
				webServer.password="admin"
 
     

                [[proxies]]
                name = "dfsdafsaf"
                type = "http"
                localIP = "127.0.0.1"
                localPort = 80
                customDomains = ["*.wlphp.com"]
